### ISSUE TITLE
Cupertino Pack for .Clocks is not Launching after purchase from Windows Store

### ISSUE THREAD

**Issue by jbaptist777** [hereafter/powergadgets#1]
I have performed a "wsreset" on my system and the app is still not launching (or showing up in the Windows Start Menu.  There is "no sign" of the app on my system at all.

Can you assist?
Jbaptist777@gmail.com

**Comment by jbaptist777** [comment]
Nevermind. I got the app running but it is useless as it is not resizeable.  Robbery.

**Comment by hereafter** [comment]
I am working on launching experience to make it more usable.
right now it relies on .Clock gadget picker of another package

it has 3 sizes, in the right context menu.
small, medium and large
