### ISSUE TITLE
Uninstalling Clocks

### ISSUE THREAD

**Issue by FrancisBiss** [hereafter/powergadgets#4]
Hi, I can't find a way to uninstall .Clocks from my Win10.  Can you please help?
Thanks

**Comment by hereafter** [comment]
.Clocks is a standard app from App Store

could you please try the following method?


https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98

**Comment by FrancisBiss** [comment]
It worked. Thank you very much

------ Original Message ------
